// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u8().primaryKey(),
  queueItemId: __t.u64().name("queue_item_id"),
  videoId: __t.string().name("video_id"),
  title: __t.string(),
  thumbnailUrl: __t.string().name("thumbnail_url"),
  addedBy: __t.identity().name("added_by"),
  startedAt: __t.timestamp().name("started_at"),
  isPlaying: __t.bool().name("is_playing"),
});
