// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  videoId: __t.string().name("video_id"),
  title: __t.string(),
  thumbnailUrl: __t.string().name("thumbnail_url"),
  addedBy: __t.identity().name("added_by"),
  playedAt: __t.timestamp().name("played_at"),
});
