// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Message = __t.object("Message", {
  sender: __t.identity(),
  sent: __t.timestamp(),
  text: __t.string(),
});
export type Message = __Infer<typeof Message>;

export const NowPlaying = __t.object("NowPlaying", {
  id: __t.u8(),
  queueItemId: __t.u64(),
  videoId: __t.string(),
  title: __t.string(),
  thumbnailUrl: __t.string(),
  addedBy: __t.identity(),
  startedAt: __t.timestamp(),
  isPlaying: __t.bool(),
  pausedAtOffset: __t.u64(),
  playedItemId: __t.option(__t.u64()),
});
export type NowPlaying = __Infer<typeof NowPlaying>;

export const PlayedItem = __t.object("PlayedItem", {
  id: __t.u64(),
  videoId: __t.string(),
  title: __t.string(),
  thumbnailUrl: __t.string(),
  addedBy: __t.identity(),
  playedAt: __t.timestamp(),
});
export type PlayedItem = __Infer<typeof PlayedItem>;

export const QueueItem = __t.object("QueueItem", {
  id: __t.u64(),
  videoId: __t.string(),
  title: __t.string(),
  thumbnailUrl: __t.string(),
  addedBy: __t.identity(),
  addedAt: __t.timestamp(),
  position: __t.u32(),
});
export type QueueItem = __Infer<typeof QueueItem>;

export const Reaction = __t.object("Reaction", {
  id: __t.u64(),
  identity: __t.identity(),
  emoji: __t.string(),
  sentAt: __t.timestamp(),
  playedItemId: __t.option(__t.u64()),
});
export type Reaction = __Infer<typeof Reaction>;

export const RoomSettings = __t.object("RoomSettings", {
  id: __t.u8(),
  messagesClearedAt: __t.timestamp(),
});
export type RoomSettings = __Infer<typeof RoomSettings>;

export const Typing = __t.object("Typing", {
  identity: __t.identity(),
  typingAt: __t.timestamp(),
});
export type Typing = __Infer<typeof Typing>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  online: __t.bool(),
});
export type User = __Infer<typeof User>;

