// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddToQueueReducer from "../add_to_queue_reducer";
import PlayNextReducer from "../play_next_reducer";
import RemoveFromQueueReducer from "../remove_from_queue_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetNameReducer from "../set_name_reducer";
import TogglePlaybackReducer from "../toggle_playback_reducer";

export type AddToQueueParams = __Infer<typeof AddToQueueReducer>;
export type PlayNextParams = __Infer<typeof PlayNextReducer>;
export type RemoveFromQueueParams = __Infer<typeof RemoveFromQueueReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type TogglePlaybackParams = __Infer<typeof TogglePlaybackReducer>;

